documentation.md

Super interesting project, and really well written documentation! Hope this bit of copy edit helps.

Documentation Copy Edit

---

README.md

Slightly better English

---

src/skin_conf.rs

3bf432fd6876f60c4ffdc47297fe960250145d83 broke compilation

Fix compilation

---

src/status.rs

Remove some code duplication in Screen::write_status_err

Avoid code duplication in status.rs

---

src/conf.rs

Make it explicit that $EDITOR needs to be exported.

---

src/cli.rs
src/conf/conf.rs
src/conf/mod.rs
src/conf/toml.rs
src/errors.rs
src/lib.rs
src/verb/builtin.rs
src/verb/external_execution.rs
src/verb/internal_execution.rs
src/verb/mod.rs
src/verb/verb.rs
src/verb/verb_conf.rs
src/verb/verb_execution.rs
src/verb/verb_store.rs

removing the useless step of VerbConf and VerbConfExecutionType

refactor verb initialization from conf

---

release.sh

As discussed , This is for better check of the release version with script.

Add version file

---

website/docs/tricks.md

Hey,
first of all thanks for making this awesome piece of software! 
Since I found no integration plugin for vim, I created a small one. To help people looking for vim integration as well, I added a reference to the plugin in the tips and tricks section of the docs on the website.
PS: Super sweet that one can join multiple configuration files for broot via the command line flag. However, this info was hidden in the help section and not mentioned elsewhere. However, it is massively useful for integrations like this (I used that feature to append "enter on a file prints the path behavior" to the default configuration). It might be worth pointing that out in the launch section of the docs (next to --out and the likes). Let me know, if I can help..

Docs: Vim integration plugin

---

src/display/cell_size.rs

Fix building error on FreeBSD host

---

website/docs/modal.md

Vim mode docs: Repair <code> formatting

---

resources/default-conf.hjson

There was a lot of mixed hard and soft tabs, inconsistent tab widths, and incorrect indentation

fix formatting of default config file

---

website/docs/tricks.md

The author has moved development to GitHub. See:
https://github.com/lstwn/broot.vim/pull/1

Update broot.vim link

---

src/pattern/tok_pattern.rs

bugfix: fix `TokPattern::find_ranges` to solve #504

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/cli/args.rs
src/tree/tree_options.rs

--sort-by-type-dirs-first --sort-by-type-dirs-last 

---

resources/default-conf/conf.hjson
src/app/app_context.rs
src/conf/conf.rs
src/conf/file_size.rs
src/conf/mod.rs
src/content_search/mod.rs
src/content_search/needle.rs
src/pattern/content_pattern.rs
src/pattern/content_regex_pattern.rs
src/pattern/input_pattern.rs
src/pattern/pattern.rs

make content search max file size configurable

---

src/file_sum/sum_computation.rs
src/path/special_path.rs
src/tree_build/builder.rs
website/docs/conf_file.md

Hi there! In my projects I have several hidden folders that I need to see at all times. I noticed that there is a `hide` option for special paths, but no `no-hide` option. So this option has been added. I hope you'll find it useful.

Add no-hide option to special paths

---

Cargo.lock
Cargo.toml
src/errors.rs
src/image/image_view.rs
src/image/mod.rs
src/image/svg.rs

Render SVG files as images in preview

---

CHANGELOG.md
src/app/panel_state.rs
src/display/displayable_tree.rs
src/hex/hex_view.rs
src/pattern/tok_pattern.rs
src/preview/preview.rs
src/preview/preview_state.rs
src/tree/tree.rs
src/tree/tree_line.rs
src/tree_build/bline.rs
src/verb/external_execution_mode.rs
website/docs/common-problems.md
website/docs/input.md

Corrects some typos in the repository.

Correct some typos

---

src/display/displayable_tree.rs
src/display/matched_string.rs

left-elision of path when path/name doesn't fit

---

resources/default-conf/catppuccin-mocha.hjson

Initial Catppuccin Mocha theme, I tried my best to stick to the Styling Guide found [here](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md).
Enjoy using it!

new theme: Catppuccin Mocha

---

src/conf/mod.rs
src/path/from.rs

optional env var setting the directory for broot conf

BROOT_CONFIG_DIR

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/app/app.rs
src/app/app_context.rs

if given a file as argument, open it in preview

---

CHANGELOG.md
src/command/parts.rs
src/pattern/input_pattern.rs
src/pattern/pattern_parts.rs
src/pattern/regex_pattern.rs

escape space and colon in automatic preview filtering

---

src/app/panel_state.rs
src/cli/args.rs
src/tree/tree_options.rs
src/tree_build/builder.rs
src/verb/internal.rs
src/verb/verb_store.rs
website/docs/conf_verbs.md
website/docs/tree_view.md

This PR aims to address issue https://github.com/Canop/broot/issues/670
Thanks for creating and maintaining this tool!

Add `toggle_tree` flag to show only items in the current dir

---

src/verb/internal_focus.rs

solve symlink on :panel_right

---

src/shell_install/mod.rs

write installed flag file on --install

---

Cargo.lock
Cargo.toml
src/browser/browser_state.rs
src/cli/args.rs
src/cli/mod.rs
src/tree_build/builder.rs
src/verb/internal.rs
src/verb/verb_store.rs
website/docs/conf_verbs.md

Stage all directories

---

src/display/permissions.rs

add support for setuid, setgid and sticky bits

---

website/docs/install-br.md

https://github.com/Canop/broot/issues/827

website: amend `install-br.md` with a note for nushell

---

website/docs/staging-area.md

Hi,
I was looking for a way to add multiple files to the staging area. Apparently `ctrl-A` does the trick so I've added it the documentation.
Don't hesitate to correct it if needed. Thanks

Documentation: adding all files to staging area

---

src/app/app.rs
src/command/completion.rs
src/verb/verb_store.rs

fix some verb cycling problems

---

src/git/status.rs

I mark on git ignored files when git file infos are shown

---

resources/icons/nerdfont/data/icon_name_to_icon_code_point_map.rs
resources/icons/vscode/data/extension_to_icon_name_map.rs
resources/icons/vscode/data/icon_name_to_icon_code_point_map.rs

make it's icon an elepant.
Not sure if the elephant is the official logo but it's in the std lib, [here](https://github.com/nushell/nushell/blob/983014cc40e6a96548c731b7de26e3a1a70d6426/crates/nu-std/std/mod.nu#L185)

nushell icon

---

src/app/panel_state.rs
src/command/completion.rs
src/command/panel_input.rs
src/command/sequence.rs
src/verb/execution_builder.rs
src/verb/verb_store.rs

This was until now only done on key events.
Might fix #926

Filter verbs by panel type

---

src/git/ignore.rs

fix .ignore files ignored outside of git directories

---

Cargo.toml
src/image/source_image.rs
src/image/svg.rs

Update resvg to v0.44

---

src/app/app.rs
src/app/cmd_result.rs
src/app/panel_state.rs
src/browser/browser_state.rs
src/stage/stage_state.rs

clear cache when files are deleted in staging area

---

src/app/app.rs
src/app/app_state.rs
src/app/panel.rs
src/app/panel_state.rs
src/browser/browser_state.rs
src/watcher.rs

This greatly improves watching perfs

don't ask notify to watch the tree: we're doint it

---

Cargo.lock
Cargo.toml
src/app/app.rs
src/app/app_context.rs
src/cli/args.rs
src/net/mod.rs
src/shell_install/nushell.rs
src/verb/execution_builder.rs

--listen-auto launch arg, for a random server name

---

CHANGELOG.md
src/command/panel_input.rs

Completion back tab
