Canop/broot

- src/errors.rs
I also opened https://github.com/rust-lang/regex/issues/562 in the hope in will help avoid string manipulations on error messages in the future
> Detailed error message on invalid regex

- src/browser_states.rs
- src/commands.rs
- src/flat_tree.rs
This PR adds the ability to use backtab (`Shift+Tab`) to select the previous match as requested in [Issue 27](https://github.com/Canop/broot/issues/27).
I tried to implement this a while ago, but couldn't find a way to get the key combination working. I then created a minimal test case for this key combination using crossterm and it still didn't work.
Then I tried another terminal emulator and finally got it working.
To conclude:
- This didn't work in my testing with konsole (may be related to my settings, but I couldn't make the key combination `Shift+Tab` work in konsole). Maybe someone else can test this change with konsole to see if it works with their settings.
- This works in my current terminal emulator alacritty without any further setup required.
This PR also potentially …
> Add support for using backtab to select the previous match

- src/shell_bash.rs
In bash and zsh, `$(<x)` expands to the contents of the file `x` without needing to invoke a subprocess.
Shellcheck passes for bash. I don't have a zsh shellcheck, but I did confirm that it works and it is a documented feature.
Shellcheck warns this is undefined for POSIX sh and unsupported by dash, but the script doesn't claim to be supported by those as it is.
I'm not a fish user, but I don't see a similar operator for fish while skimming its manual.
> bash: replace `cat` invocation with built-in

- src/shell_install/fish.rs
Try `~/.config/fish` before relying on app dirs.
Fixes #88.
> Fix Fish function installation on macOS

- website/docs/documentation/installation.md
Just lifted the Homebrew section from the [exa docs](https://github.com/ogham/exa/blob/master/README.md). Feels pretty standard to have instructions per package manager.
Project looks great, btw.
> docs - add Homebrew to installation instructions

- src/app.rs
- src/app_state.rs
- src/browser_states.rs
- src/browser_verbs.rs
- src/commands.rs
- src/patterns.rs
- src/task_sync.rs
- Fixed many unidomatic uses of "if let Some(x) = thing"
- Added standard trait implementations and other interface refactorings (for instance, moving "from(thing)" to From<Thing>. All of these do not affect the use of these interfaces.
- Replaced &Box<dyn Trait> with &dyn Trait, where relevant.
- App::run and App::end now take App by value, to enforce that they should only be called once.
- Replaced `loop` with `for event in rx_events` in App::run.
- Touched files were rustfmt'd
> Numerous minor refactorings

- website/docs/documentation/installation.md
broot is now present in MacPorts; adding instruction for installing it that way to the website docs.
> website: add information on installing broot via MacPorts

- src/browser_states.rs
Closes #147.
This implements the fix I posted in a comment in the discussion.
> Only update filtered_tree if the new one is Some

- src/help_content.rs
The proposed symbols probably have much better font coverage (Unicode block in Basic Plane rather than in Supplementary one), at least on my systems.
> Replace up- and downward arrow symbols in help

- src/app.rs
- src/app_state.rs
- src/browser_states.rs
- src/displayable_tree.rs
- src/help_states.rs
- src/io.rs
- src/main.rs
- src/screens.rs
- src/status.rs
- src/verbs.rs
Fixed #162; see that issue for a detailed design discussion, including a reproduction of the bug this fixes.
I did my best to keep this PR minimal; the biggest thing it required was replacing `&mut W` with `&mut impl io::Write` pretty much everywhere. I did rustfmt the lines that I touched, but I did my best to not rustfmt unrelated parts of files.
- Added `WriteCleanup`, an RAII wrapper for doing cleanup with `io::Write`
- Includes test
- Replaced many uses of `W` (an stderr alias) with `&mut impl io::Write`
- Removed App::end. The functionality automatically happens with Drop handlers.
- Rustfmt'd modified files.
> Added write cleanup methods to ensure the terminal is correctly restored

- Cargo.lock
- Cargo.toml
- src/browser_verbs.rs
- src/external.rs
- src/help_verbs.rs
- src/verb_store.rs
This is a use-case I have where I want to sometimes reference things relatively. This lets me do `file:prp` and have it printed relative to the CWD.
This is just the code I use. Happy to rewrite it to your standards to upstream.
> Allow printing relative paths as well

- website/docs/documentation/configuration.md
> Close kbd tag in docs

- website/docs/index.md
The backtick on the main page includes the word 'command' instead of
just the words that make up `git status`
> Fix documentation, backtick

- src/conf/default_conf.rs
- src/verb/builtin.rs
- website/docs/conf_verbs.md
- website/docs/verbs.md
The `chmod` verb was already using `PATH`, but others were using absolute paths that don't necessarily exist on every Linux distro. For example, on NixOS there is no `/bin/rm`, so the `broot` package rewrites `/bin/` to a path in the "Nix store" (this is typical), which works just fine, but makes the UI's verb preview very verbose:
The `chmod` verb specifies `chmod` instead of `/bin/chmod` (relying on `PATH` lookup), which works just as well and has a cleaner verb preview:
I made all verbs work like `chmod` does, which cleans up the preview for me:
I also changed documentation examples to use bare executable names instead of absolute paths since it's generally more compatible with different executable locations.
> Use PATH instead of absolute paths for all verbs

- src/tree/tree_line_type.rs
Tiny improvements to avoid going in circles longer than need or not getting to the end of a long link chain due to the heuristic upper limit is kicking in.
> feat: instant break for circular symlinks

- src/conf/default_conf.rs
This fixes an issue with the default config: If you were to uncomment the `[special-paths]` table/dictionary and the `date_time_format` in the default config, you are greeted with an error `Unrecognized: YmdR` because the `date_time_format` is then parsed into the special paths table because TOML.
Basically, what the comment in the beginning warns people about.
The new order fixes that issue.
> FIX: faulty default config

- website/docs/install.md
Note: Alpine 3.13 has not been released yet, it should be till the end of this year.
> add Alpine Linux into third party repositories

- .github/ISSUE_TEMPLATE/bug_report.md
This PR improves the bug_report template to add information on how to get the log of br (copied from https://dystroy.org/broot/community/#log)
> ask for log on bug report

- src/shell_install/fish.rs
make `br` inherit completion of `broot`
https://fishshell.com/docs/current/cmds/function.html
> `-w WRAPPED_COMMAND` or `--wraps=WRAPPED_COMMAND` causes the function to inherit completions from the given wrapped command.
https://github.com/Canop/broot/issues/337
> fish completion for br

- Cargo.toml
- src/cli/clap_args.rs
Thank you for maintaining this awesome tool in advance.
Lots of cli tools written in rust have a colored help (fd, bat etc.). I think adding this tiny feature to `broot` is not a bad idea :)
( I noticed that `default-features` for clap are disabled in the `Cargo.toml`. Since the `color` feature is one of them I don't know if it was intentional disabled. )
> add colored help

- src/shell_install/bash.rs
Additionally, this contains proposed changes from #118
- use local variables to prevent accidental overwriting of variables set by the user in the current shell
- rename variables to a more descriptive name
Closes #118
> Refactor bash shell function to avoid usage of sub-shell

- man/page
I've simply added the `--color` option to the `man` page, whilst removing `--no-style`, which was seemingly removed sometime between 93b1ffcc701a7753e8376c80b0c10683f7e3e36d and 7d512894808500946a6acb6d4939d4ba1473c14d.
> Document the --color option

- website/docs/common-problems.md
[As requested](https://github.com/Canop/broot/issues/50#issuecomment-890290701), I'm documenting how to fix Broot's `alt+enter` keyboard shortcut in Windows Terminal (which binds `alt+enter` to "Toggle Fullscreen" by default).
> Document alt+enter keybinding fix for Windows Terminal

- .github/dependabot.yml
Creates update PRs similar to https://github.com/dbast/broot/pulls with history for each dependency bump etc for review.
PRs can be merged if CI is green or closed to ignore the dependency regarding auto updates.
> Add dependabot config for cargo updates

- website/docs/install.md
Broot is available in Gentoo Linux: https://packages.gentoo.org/packages/app-misc/broot
Add it to the list of distro installation instructions.
> Add Gentoo Linux installation instructions

- src/verb/builtin.rs
Added a cfg for windows for the following commands
* mkdir
* cp
* mv
* rm
Tested on Windows 11
The flags that are passed to the respective windows commands are open do discussion as I am not sure if they behave the same like in unix.
> Issue #535 program not found on windows

- src/git/ignore.rs
.git/info/exclude has equivalent syntax to .gitignore, for the purpose
of placing ignored files that are local to the current clone. This
change adds support for this file as if it were a regular .gitignore.
Signed-off-by: Ryan Gonzalez <rymg19@gmail.com>
> Treat files in .git/info/exclude as ignored

- src/task_sync.rs
While working on clippy I was checking why some crates whitelisted `drop_copy` lint, and found it was not needed here.
> Remove unneeded clippy lints whitelist

- CHANGELOG.md
- src/app/panel.rs
- src/app/state_type.rs
- src/command/panel_input.rs
- src/conf/verb_conf.rs
- src/verb/verb.rs
- website/docs/conf_verbs.md
The optional `panels` verb configuration parameter allows specifying the list of panels in which the verb can be called.
It's thus possible to define a key which works differently depending on the panel:
{
key: F8
execution: ":page_down"
panels: [preview, help, fs]
}
{
key: F8
execution: ":page_up"
}
(F8 would there do a page up in the file tree and a page down elsewhere)
> restrict verbs to specific panels

- src/shell_install/bash.rs
See https://github.com/Canop/broot/issues/206. I don't use nor know much about fish, so it would be nice if someone tested, if a similar change would work there as `command` is a shell built-in.
> Prevent `br` from using `rm` alias or function in Bash

- resources/default-conf/conf.hjson
- src/file_sum/sum_computation.rs
Avoid computing sizes of dirs for which it doesn't work (/run, /proc, and sometimes /media).
> Fix issue 637

- src/shell_install/nushell.rs
This is tiny fix for the case where a path contains white spaces in it.
Maybe @mediumrarez could double check what I am proposing is fine too?
> fix: nushell br alias fails on alt-enter if folder contains spaces

- src/shell_install/mod.rs
Fix `https://dystroy.org/broot/install` -> `https://dystroy.org/broot/install-br/` when prompting before installing the shell function.
The shell installation page is at https://dystroy.org/broot/install-br/ . It was wrongly pointing to the binary installation instructions at https://dystroy.org/broot/install , which would be useless to someone who is seeing that message after running the executable.
```
Broot should be launched using a shell function.
This function most notably makes it possible to cd from inside broot
(see https://dystroy.org/broot/install for explanations).
Can I install it now? [Y/n]
n
You refused the installation (for now).
You can still used broot but some features won't be available.
If you want the br shell function, you may either
• do broot --install
• install …
```
> Fix install-br website link

- Cargo.lock
- Cargo.toml
- src/launchable.rs
This makes broot use `/usr/bin/editor` when `$EDITOR` has not been set yet. This reduces friction and improves the new user experience.
`/usr/bin/editor` is the convention on Ubnutu. Many editors such as `/bin/ed`, `/usr/bin/vim.basic` and `/usr/bin/vim.tiny` among others use `update-alternatives` to offer themselves as providers for `/usr/bin/editor` via `/etc/alternatives/editor`. `$EDITOR` is not usually set on Ubuntu. In fact, the Ubuntu developers patched software specifically for this. [For example](https://packages.ubuntu.com/kinetic/bash), `debian/patches/bash-default-editor.diff` in `bash_5.2-1ubuntu2.debian.tar.xz` makes bash consider `/usr/bin/editor` when doing CTRL-x CTRL-e.
This PR implements this Ubuntu-like behavior. It will not change anything if `$EDITOR` is already set. …
> Fall back on /usr/bin/editor for $EDITOR

- src/shell_install/nushell.rs
Just renamed the branch. Same as [feat: expand paths passed to *Broot* in *Nushell* by stevenxxiu · Pull Request #677 · Canop/broot](https://github.com/Canop/broot/pull/677).
Forward all args besides `--outcmd`.
> fix: expand the path passed to *Broot*

- CHANGELOG.md
- Cargo.toml
- src/app/selection.rs
- src/conf/verb_conf.rs
- src/launchable.rs
- src/verb/external_execution.rs
- website/docs/conf_verbs.md
Broot runs in an "alternate terminal".
By default,  broot switches back to the normal terminal during the execution of a program it launches, then back to its alternate terminal on end of the external process.
In some cases, this adds an unnecessary flicker.
The `switch_terminal` verb parameter, whose default value is `true`, lets you disable this behaviour.
Same goal than https://github.com/Canop/broot/pull/692 but with some different data structures.
> switch_terminal verb config parameter

- Cargo.lock
- src/app/app.rs
- src/browser/browser_state.rs
- src/task_sync.rs
On Windows, powershell sends to broot a Resize event after it was launched, which interrupts its task (for example a filtering provided with `--cmd`).
Asking broot to wait for 10ms before cleaning its event queue and then working on its task queue solves the problem.
Fix #699
> clear events after delay on windows

- src/file_sum/sum_computation.rs
Dir size computation is disabled in /proc and /run by: https://github.com/Canop/broot/commit/aecfe73ba9947e2a1c04f70526cab87e49f4baef
However, usb disks are auto-mounted under /run/media, so let's allow dir size in this dir.
FIX: https://github.com/Canop/broot/issues/704
> Allow dir size computation in /run/media

- website/docs/install.md
Scoop is a windows package manager, broot has been available through it for a while.
> Add scoop to 3rd party repositories on the website docs

- src/shell_install/mod.rs
- src/shell_install/powershell.rs
A PowerShell br function install module based on [AeliusSaionji's br function](https://github.com/Canop/broot/issues/460#issuecomment-1303005689) as suggested in #625 and #159.  It follows the same conventions as the other install modules. The function is added to the $HOME\Documents\WindowsPowerShell\Profile.ps1 profile.
I tested this on two Windows 10 machines but not on Windows 11.
> Powershell br function install

- src/shell_install/powershell.rs
Fix a [bug](https://github.com/Canop/broot/pull/720#issuecomment-1637196067) where the install fails if the WindowsPowerShell directory already exists but the Profile file does not.  The error is raised because fs::create_dir fails if the target directory already exists. fs::create_dir_all does not.
> fix Powershell br function install error

- src/command/parts.rs
- website/docs/input.md
> allow unescaped '::' in pattern

- src/verb/execution_builder.rs
- src/verb/internal_focus.rs
- website/docs/conf_verbs.md
Initial attempt at #760. This works well in my testing.
> Add `{git-root}` substitution

- CHANGELOG.md
- resources/default-conf/verbs.hjson
- src/app/selection.rs
- src/command/panel_input.rs
- src/conf/verb_conf.rs
- src/content_search/mod.rs
- src/content_type/extensions.rs
- src/content_type/magic_numbers.rs
- src/content_type/mod.rs
- src/lib.rs
- src/verb/file_type_condition.rs
- src/verb/mod.rs
- src/verb/verb.rs
- src/verb/verb_store.rs
- website/docs/conf_verbs.md
- website/docs/install.md
- website/docs/tricks.md
This makes it possible, for example, to have text files open in the same terminal on 'enter':
```Hjson
{
invocation: edit
key: enter
shortcut: e
execution: "/usr/bin/nvim +{line} {file}"
apply_to: text_file
leave_broot: false
}
```
Fix #764
> Extend 'apply_to' with 'text_file' and 'binary_file'

- src/app/app.rs
A previous change adding some PS-specific fixes that affected all Windows instances when -c was called. However if -c was called with an incomplete command (and therefore should put broot into an interactive state) this had the effect of hanging the app.
This should fix #776 . It does make me a bit uncomfortable that this means that you can end up in interactive mode in two different ways. One by running `br` regularly and one with `-c "Incomplete command"` except in the latter case, the window hasn't been resized as the `Resize` event gets dropped. However until I see manifestations of this behaviour I think this might be hacky enough to be ok?
I've tested this with bash and PS, using `-c` and without, and it all seems fine.
> Fix Windows crash when running -c

- Cargo.lock
- Cargo.toml
- src/permissions/permissions_unix.rs
"users" is unmaintained ([RUSTSEC-2023-0040](https://rustsec.org/advisories/RUSTSEC-2023-0040)) and has a listed vulnerability ([RUSTSEC-2023-0059](https://rustsec.org/advisories/RUSTSEC-2023-0059)). Switch to the maintained and updated fork "[uzers](https://github.com/rustadopt/uzers-rs)", and upgrade to [0.11.3](https://github.com/rustadopt/uzers-rs/releases/tag/v0.11.3) that has the fix for RUSTSEC-2023-0059.
> RUSTSEC-2023-0040, RUSTSEC-2023-0059: Switch dependency from "users" to "uzers"

- resources/default-conf/conf.hjson
- src/app/app.rs
- src/app/app_context.rs
- src/conf/conf.rs
- src/lib.rs
- src/terminal.rs
- src/verb/execution_builder.rs
Allow automating the terminal's title change.
Add this in configuration:
###############################################################
#
terminal_title: "🐄 {file} "
Fix #794
> terminal_title parameter in config

- src/shell_install/nushell.rs
> fix: ✨ nushell deprecation

- src/verb/internal_focus.rs
Fix #809
It's thus possible that issue #804 exists on Windows, I can't test that.
> don't canonicalize paths on windows on new panels

- resources/default-conf/conf.hjson
- src/app/app.rs
- src/app/app_context.rs
- src/conf/conf.rs
- src/display/luma.rs
- website/docs/conf_file.md
Fix #813
I'm not really sure there are many use cases for this, and I might gate it behind a configuration flag if I suspect there might be unwanted side effects.
> Sync broot working dir with current panel's root

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- resources/default-conf/conf.hjson
- src/app/app_context.rs
- src/conf/conf.rs
- src/conf/mod.rs
- src/conf/special_handling_conf.rs
- src/errors.rs
- src/file_sum/sum_computation.rs
- src/path/special_path.rs
- src/skin/help_mad_skin.rs
- src/skin/purpose_mad_skin.rs
- src/skin/status_mad_skin.rs
- src/tree_build/bline.rs
- src/tree_build/builder.rs
- website/docs/conf_file.md
A special paths entry is defined by 3 parameters: `show`, `list`, and `sum`.
Each of them can be `default`, `always`, or `never`.
Example configuration:
```Hjson
special_paths: {
"/media" : {
list: "never"
sum: "never"
}
"~/.config": { "show": "always" }
"trav": {
show: always
list: "always",
sum: "never"
}
"~/useless": { "show": "never" }
"~/my-link-I-want-to-explore": { "list": "always" }
}
```
Fix #687
Fix #669
> new definition of special paths

- src/shell_install/nushell.rs
_Nushell_ deprecated the use of automatic spreading lists in favor of the `...` syntax, which throws an error each time _broot_ launched via `br` is closed.
This PR just update the syntax accordingly.
> Update nushell.rs to fix error on exit

- Cargo.lock
- Cargo.toml
- src/app/app_context.rs
- src/conf/conf.rs
- src/image/image_view.rs
- src/kitty/image_renderer.rs
- src/kitty/mod.rs
- website/docs/conf_file.md
Use one of those settings:
```
kitty_graphics_transmission: chunks
kitty_graphics_transmission: temp_file
```
The faster `temp_file` mode is the current default. Downside is it won't work for a remote broot execution.
May solve #789
> use temp_file transmission medium for kitty img

- src/shell_install/nushell.rs
Enables `use /path/to/br *` ([manual](https://www.nushell.sh/book/modules.html#dumping-files-into-directory)) without breaking `source /path/to/br` (nushell/nushell#6571). I haven't tested in Rust yet (only Nu).
> Export nushell command

- src/app/panel_state.rs
- src/browser/browser_state.rs
- src/cli/args.rs
- src/cli/mod.rs
- src/filesystems/filesystems_state.rs
- src/help/help_state.rs
- src/preview/preview_state.rs
- src/shell_install/util.rs
- src/stage/stage_state.rs
- src/verb/execution_builder.rs
- src/verb/internal.rs
- src/verb/internal_focus.rs
- src/verb/internal_select.rs
- src/verb/mod.rs
- src/verb/verb.rs
- src/verb/verb_store.rs
- src/verb/write.rs
Fix: #825
Add a `--verb-output` launch argument which takes a path to a file (which will be created if necessary)
Add a  `:write_output` internal which allows adding a line to that file. No escaping is done (contrary to what happens with `--outcmd`).
Add a `:clear_output` internal which clears the file.
Here are 2 examples of verbs:
```
{
invocation: "wc {cmd}"
execution: ":write_output wc:{cmd} {file-stem}.bro"
}
{
key: alt-w
cmd: ":clear_output;:write_output {directory};:quit"
}
```
The first one is called with an input like `:wc hop` which appends to the output a line like `wc:hop main.bro`. 
The second one makes the content of the output file the directory closest to the selection then quits. It could for example be used for a new version of the `br` shell function.
Note: Semantics …
> :write_output & :clear_output, --verb_output

- CHANGELOG.md
- bacon.toml
- resources/default-conf/conf.hjson
- resources/default-conf/skins/catppuccin-macchiato.hjson
- resources/default-conf/skins/catppuccin-mocha.hjson
- resources/default-conf/skins/dark-blue.hjson
- resources/default-conf/skins/dark-gruvbox.hjson
- resources/default-conf/skins/dark-orange.hjson
- resources/default-conf/skins/solarized-light.hjson
- resources/default-conf/skins/white.hjson
- src/app/app_context.rs
- src/conf/conf.rs
- src/preview/preview.rs
- src/preview/preview_state.rs
- src/skin/style_map.rs
- src/syntactic/syntactic_view.rs
- src/verb/execution_builder.rs
- website/docs/conf_file.md
- website/docs/skins.md
New settings:
```
###############################################################
#
#
lines_before_match_in_preview: 1
lines_after_match_in_preview: 1
```
Fix #756
> optionally show lines surrounding a match in preview

- resources/default-conf/skins/native-16.hjson
This adds the skin discussed in https://github.com/Canop/broot/issues/203. The colors depend on the underlying terminal theme, so it might be useful to have a couple known good themes to use as a baseline. This is the terminal emulator theme I've used:
```
name='Birds Of Paradise'
foreground='#e0dbb7'
background='#2a1f1d'
cursor='#e99d2a'
black='#573d26'
red='#be2d26'
green='#6ba18a'
yellow='#e99d2a'
blue='#5a86ad'
magenta='#ac80a6'
cyan='#74a6ad'
white='#e0dbb7'
brblack='#9b6c4a'
brred='#e84627'
brgreen='#95d8ba'
bryellow='#d0d150'
brblue='#b8d3ed'
brmagenta='#d19ecb'
brcyan='#93cfd7'
brwhite='#fff9d5'
```
It has good contrast and follows the ANSI color naming scheme (so the color for `red` is actually red, the brighter colors are actually brighter, etc.). I can imagine users will start …
> Add 16 color native skin

- CHANGELOG.md
- src/browser/browser_state.rs
- src/tree/tree.rs
This makes it easier to define alternatives to the standard enter on directories.
> calling :focus on the tree root goes up

- Cargo.toml
- compile-all-targets.sh
- src/browser/browser_state.rs
- src/stage/stage_state.rs
Since #803 introduced a dependency on the trash crate, broot does not compile any more on Android. This change makes the trash crate only pulled in on platforms which support it, and otherwise the trash command displays an error.
Fixes #861
> fix builds on android

- src/app/panel_state.rs
- src/verb/verb_invocation.rs
- src/verb/verb_store.rs
To remove a binding (without binding it to another verb), define a verb without any execution, for example
{
key: alt-i
}
Fix #632
> make it possible to unbind keys

- features.md
The addition of the [trash feature](https://github.com/Canop/broot/pull/882) hasn't been documented in `feature.md` so far.
> features.md: add "trash" feature

- src/shell_install/nushell.rs
XDG_RUNTIME_DIR is almost guaranteed to be living inside in-memory filesystem (tmpfs) which is much more suitable for such a create and drop temp files. On many systems /tmp is still on hard disk.
> Use XDG_RUNTIME_DIR when available

- src/browser/browser_state.rs
Fix paths being changed to UNC on Windows.
Fix #812
> don't canonicalize paths on windows when focusing a path

- src/app/app.rs
- src/app/panel.rs
- src/browser/browser_state.rs
- src/verb/internal.rs
- src/verb/verb_store.rs
This brings the `search_again` internal, which tries to fix a frequent annoyance, which is the loss of the search pattern when navigating, something I hadn't found good ergonomics for before.
`:search_again` is mapped by default to `ctrl-s`.
- When there's already an active filtering, and it wasn't complete, make it total (it thus does what the `total_search` internal was doing).
- When there's no active filtering, brings back the last used.
Main use case: you search, have a lot of matches, focus a folder to look inside, then you can bring back the search pattern with ctrl-s.
I'd be very interested in tester feedback on this.
> search_again internal

- src/content_type/extensions.rs
> remove "bak" from binary files extensions list

- Cargo.lock
- Cargo.toml
- src/app/app_context.rs
- src/app/panel_state.rs
- src/command/panel_input.rs
- src/terminal.rs
- src/verb/execution_builder.rs
- src/verb/external_execution.rs
- src/verb/internal_focus.rs
- src/verb/internal_select.rs
- src/verb/verb.rs
- website/docs/conf_verbs.md
Allow verbs like 
{
key: ctrl-esc
execution: ":focus {initial-root}"
}
(if the kitty keyboard protocol is enabled)
Fix #919
> Initial root

- src/git/ignore.rs
Files called `.ignore` with the syntax of gitignore files are now read and used just like `.gitignore` files.
When, at the same level, broot finds rules from both a `.ignore` and a `.gitignore` files, the `.ignore` is the decisive one (it's assumed to be personal and meant to override the shared `.gitignore` file.
Eg I can have a global `.gitignore` file with 
dys-notes.*
which helps me have notes everywhere and not sharing them.
And I can have a `.ignore` file, which reveals some of those files in broot:
!dys-notes.md 
Fix #613
> Allow ignore/unignore rules in .ignore

- .gitignore
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/app/panel_state.rs
- src/app/standard_status.rs
- src/browser/browser_state.rs
- src/git/ignore.rs
- src/verb/internal.rs
- src/verb/verb_store.rs
- website/docs/conf_file.md
- website/docs/css/details.css
- website/docs/index.md
- website/docs/js/details.js
- website/docs/tree_view.md
- website/mkdocs.yml
The list of ignore files applicable to a directory contains
- the global `.gitignore` file (if any)
- all the `.ignore` files found in the current directory and in parents
- the `.git/info/exclude` file of the current git repository
- all the `.gitignore` files found in the current directory and in parents but not outside  the current git repository (i.e. not in git repositories containing the current git repository)
Deeper file have a bigger priority.
`.ignore` files have a bigger priority than `.gitignore` files.
---
Those rules allow for example having personal `my-notes.*` files always ignored by git but visible in broot, with only global files:
In `~/.config/git/ignore` :
```
.ignore
my-notes.*
```
In `~/.ignore` :
```
!my-notes.*
```
(note the `!` before the pattern)
> Non erased global ignore

- Cargo.lock
- Cargo.toml
- src/app/cmd_result.rs
- src/browser/browser_state.rs
- src/filesystems/filesystems_state.rs
- src/lib.rs
- src/trash/mod.rs
- src/trash/trash_sort.rs
- src/trash/trash_state.rs
- src/trash/trash_state_cols.rs
- src/verb/internal_focus.rs
- website/docs/css/extra.css
- website/docs/index.md
Trash screen (which you obtain with `:open_trash` on compatible platforms) now has 2 optional columns: one for the size and one for the deletion date.
Those internals work as expected: `:toggle_date`, `:toggle_size`, `:sort_by_date`, `:sort_by_size`.
> size & date in trash screen

- src/app/app.rs
- src/app/panel_state.rs
- src/verb/internal.rs
- src/verb/verb.rs
- src/verb/verb_store.rs
This was requested in #926.
This internal allows a verb which would work
* on staged files when the staging area is open, even when it's not focused
* on the selection when there's no open staging area 
{
invocation: rm
cmd: ":focus_staging_area_no_open;:trash {file}"
}
Fix #926
> focus_staging_area_no_open internal

- Cargo.lock
This gets https://github.com/bytecodealliance/rustix/pull/1147, a fix that makes things work on Android again (see #940 - this is the patch Termux carries when building latest broot).
> Update rustix from 0.38.34 to 0.38.37

- src/kitty/detect_support.rs
This PR extends the existing approach which checks for WezTerm and Kitty terminals to also support Ghostty. Ghostty is a terminal (currently in closed beta, but ~600 stars) that also implements support for Kitty graphics protocol.
I have also adapted your terminal checking code and [ported my own CLI application](https://github.com/pls-rs/pls/blob/9ba7d88ef4765b0b3f4ce0a3ffede89dd7500895/src/gfx/kitty.rs#L24-L49), [`pls`](https://pls.cli.rs). Thank you!
> Add image rendering support for Ghostty

- Cargo.lock
- Cargo.toml
- src/app/app.rs
- src/app/app_context.rs
- src/cli/mod.rs
- src/conf/conf.rs
- src/image/image_view.rs
- src/kitty/image_renderer.rs
- src/kitty/mod.rs
In order to display images with the Kitty protocol, broot creates temp files at the optimal dimensions and gives them to the terminal.
A problem with this approach is that those images may take a lot of space, especially if you're on linux and never reboot, as the `/tmp` folder is usually emptied on reboot.
With this commit:
- broot, on quitting, deletes all the temp files it created
- broot has a maximum number of temp files (defined with the `kept_kitty_temp_files` config entry) and removes the least recently used one when the max is reached
> remove temp files used by kitty

- Cargo.lock
- Cargo.toml
- bacon.toml
- src/display/matched_string.rs
- src/kitty/image_renderer.rs
- src/task_sync.rs
> Dont use the onig crate

- src/shell_install/fish.rs
As stated in [fish documentation on eval](https://fishshell.com/docs/current/cmds/eval.html):
> If the command does not need access to stdin, consider using [source](https://fishshell.com/docs/current/cmds/source.html) instead.
This has been tested manually on latest fish, though it should be compatible with any relevant version.
> Remove eval usage in fish launcher

- src/net/server.rs
* Add a --force flag for server in the case the socket already exists and you need to forcefully
delete the file. Fixes #969.
> Add --server --force flag.

- src/tree/tree.rs
A refresh operation occurs on many cases, for example after execution of an external program (including an editor) because those programs often change files.
Refresh should be fast, which is why it's never doing a "total search". The bug is that the tree didn't know it wasn't anymore in total search mode, so it prevented a total search by pretending it wasn't needed.
Fix #985
With this fix, you can launch a total search after refresh (eg with <kbd>Ctrl</kbd>-<kbd>S</kbd>)
> Fix total search impossible after refresh

- src/conf/verb_conf.rs
- src/verb/external_execution.rs
- src/verb/verb_store.rs
By default, the tree is refreshed after execution of an external command because files are often modified by such command.
To prevent refresh, add this to the verb definition:
refresh_after: false
Fix #987
> refresh_after verb parameter

- features.md
- src/app/app_context.rs
- src/app/panel_state.rs
- src/errors.rs
- src/task_sync.rs
- website/docs/conf_file.md
- website/docs/conf_verbs.md
Found via `typos --hidden --format brief`
> Fix typos again

- src/shell_install/nushell.rs
Without this you get errors upon loading:
```nu
Error: nu::parser::variable_not_found
× Variable not found.
╭─[/Users/liz/.config/nushell/autoload/br.nu:76:8]
75 │     if $show_root_fs { $args = ($args | append $'--show-root-fs') }
76 │     if $max_depth != null { $args = ($args | append $'--max-depth=($max_depth)') }
·        ─────┬────
·             ╰── variable not found.
77 │     if $sort_by_count { $args = ($args | append $'--sort-by-count') }
╰────
```
> Fix missing `--max-depth` argument in nushell install

- src/shell_install/nushell.rs
The nushell launcher is currently broken:
```
> br
error: invalid value 'false' for '--max-depth <MAX_DEPTH>': invalid digit found in string
```
The `max-depth` argument needs to be type-hinted to integer, so that if its blank it defaults to `null`, as opposed to `false`.
Thanks for the awesome program, really enjoying it!
> Add type hint to `max-depth` for nushell launcher

- Cargo.lock
- Cargo.toml
- src/browser/browser_state.rs
- src/verb/internal_focus.rs
The fixed bug:
When a verb is defined with the focus internal and an argument (eg execution: ":focus {git-root}") then the destination computation is done with starting path being the parent of the selected path.
Fix #1009
> fix focus with conf arg going up if root selected

- Cargo.lock
- Cargo.toml
- src/app/panel_state.rs
- src/lib.rs
- src/preview/mod.rs
- src/preview/preview.rs
- src/preview/preview_state.rs
- src/tty/mod.rs
- src/tty/tline.rs
- src/tty/tline_builder.rs
- src/tty/trange.rs
- src/tty/tstring.rs
- src/tty/tty_view.rs
- src/verb/internal.rs
- src/verb/verb_store.rs
- website/docs/conf_verbs.md
Allows previewing a file containing ANSI escape codes for styling.
Fix #1019
> add the preview_tty verb, for text with ANSI codes

- website/docs/conf_verbs.md
- website/docs/tree_view.md
Hi, new user here. Thanks for the tool.
Replace references to the old verb `toggle_git_ignore` with the new verb `toggle_ignore` introduced in v1.42.0.
(Not covered here: I'm unable to execute the old verb `:toggle_git_ignore`. Not a big deal, and hopefully the documentation will resolve any confusion from new users.)
I also included a commit to clarify a sentence about verb execution. Let me know if you want that removed or split from the PR.
> Update documentation with preferred name toggle_ignore

- src/kitty/detect_support.rs
Following revert in https://github.com/Canop/broot/commit/46be2cdb76c96b0e815575a63c520cc0edb928fc there were some lingering crate uses introduced by https://github.com/Canop/broot/commit/db4a05f387937ee41b976b9d305605bfeb122534 and not used anymore, triggering the following warning:
```
warning: unused imports: `lazy_regex::regex_captures` and `process::Command`
--> src/kitty/detect_support.rs:4:5
|
4 |     lazy_regex::regex_captures,
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^
...
7 |         process::Command,
|         ^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: `broot` (lib) generated 1 warning (run `cargo fix --lib -p broot` to apply 1 suggestion)
```
> fix: unused dependencies in kitty/detect_support

- src/syntactic/syntactic_view.rs
Similar to #1042, but for text previews.
If the preview background/foreground is set to none in the skin file, it should render as transparent rather than defaulting to a specific color.
selection_bg and match_bg should remain visible though, so we can continue using Color::AnsiValue for those two.
What do you think ?
> fallback to transparent background for text preview

- Cargo.toml
- build.rs
- src/browser/browser_state.rs
- src/stage/stage_state.rs
- src/verb/verb_store.rs
279a4af removed the `trash` feature in favor of just using conditional compilation for supported platforms; but it didn't actually compile on platforms not supported by the `trash` crate.
This fixes compilation in these cases. Rather than compile out the trash command altogether, this prints an error message if trash is not supported on the platform. This way, key bindings and such can still work across platforms.
> fix non-trash platforms

- Cargo.lock
- Cargo.toml
- src/errors.rs
- src/image/double_line.rs
- src/image/image_view.rs
- src/image/mod.rs
- src/image/source_image.rs
- src/image/svg.rs
- src/image/zune_compat.rs
- src/kitty/image_renderer.rs
- src/preview/preview.rs
Use the zune-image crate instead of the image one, unless when zune-image doesn't work (gif, tiff, webp, etc.).
This improves the rendering speed of image preview.
> use zune-image for improved speed
